on:
  push:
    branches:
      '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Matrix Transpose Code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Acquire build dependencies
        run: |
          sudo apt-get install -y cmake g++ libmpich-dev

      - name: Build the code
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Run the code on a single rank
        run: |
          cd build
          mpiexec -n 1 ./build/transpose

      - name: Run the code on two MPI ranks
        run: |
          cd build
          mpiexec -n 2 ./build/transpose

      - name: Run the code on three MPI ranks
        run: |
          cd build
          mpiexec -n 3 ./build/transpose

      - name: Run the code on four MPI ranks
        run: |
          cd build
          mpiexec -n 4 ./build/transpose
